/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HatModel = React.memo(function HatModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/sci-fi_computer.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.015;
  });
  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[0.8, 0.8, 0.8]}
      rotation={[0.3, 0.5, 0]}
      position={[0, -0.4, -1]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_screen_0.geometry}
          material={materials.screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_computer_0.geometry}
          material={materials.computer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_keyboard_0.geometry}
          material={materials.keyboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_keys_0.geometry}
          material={materials.keys}
        />
      </group>
    </group>
  );
});

export default HatModel;
useGLTF.preload("/models/sci-fi_computer.glb");
