/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HatModel = React.memo(function HatModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/k-vrc.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.025;
  });
  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[2.5, 2.5, 2.5]}
      rotation={[0.3, 0.5, 0]}
      position={[0, -0.9, -1]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.body}
        rotation={[-Math.PI / 2, 0, 0]}
      />

      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.466}
      /> */}

      {/* <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_screen_0.geometry}
          material={materials.screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_computer_0.geometry}
          material={materials.computer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_keyboard_0.geometry}
          material={materials.keyboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.scifi_computer_keys_0.geometry}
          material={materials.keys}
        />
      </group> */}
    </group>
  );
});

export default HatModel;
useGLTF.preload("/models/k-vrc.glb");
